name:                qnap-decrypt
version:             0.3.0
github:              "alexkazik/qnap-decrypt"
license:             BSD3
author:              "ALeX Kazik"
maintainer:          "alex@kazik.de"
copyright:           "2018 ALeX Kazik"

synopsis:            Decrypt files encrypted by QNAP's Hybrid Backup Sync
category:            Cryptography

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/alexkazik/qnap-decrypt#readme>

dependencies:
- base >= 4.10 && < 5
- binary >= 0.6.4 && <0.9
- bytestring >= 0.10.0.0 && <0.11
- cipher-aes128 >= 0.1 && <0.8
- conduit >= 1.3.0 && <1.4
- conduit-extra >= 0.3.0 && <1.4
- crypto-api >= 0.13.3 && <0.14
- directory >= 1.2.7 && <1.4
- streaming-commons >= 0.1.0.0 && <0.3
- tagged >= 0.8.5 && <0.9
- utf8-string >= 1.0.1.1 && <1.1

library:
  source-dirs: src

executables:
  qnap-decrypt:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - qnap-decrypt
    - filepath >= 1.4.1.2 && <1.5
    - optparse-applicative >= 0.14.2.0 && <0.15

tests:
  qnap-decrypt-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - qnap-decrypt
    - filepath >= 1.4.1.2 && <1.5
    - hspec >= 2.4.8 && <2.6
    - HUnit >= 1.6.0.0 && <1.7
    - temporary >= 1.2.1.1 && <1.3

data-files:
- test/encrypted/*
- test/reference/*
